name: Deploy Astro Portfolio

on:
  push:
    branches:
      - main   # Change if your default branch is not main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages   # Required for deploy-pages action

    steps:
      # 1 Checkout the repo
      - uses: actions/checkout@v4

      # 2Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3 Install dependencies
      - run: npm install

      # 4 Build Astro site
      - run: npm run build

      # 5 Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
